name: ascendere_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  generic_bloc_provider: ^1.0.8
  firebase_auth: ^0.15.4
  google_sign_in: ^4.1.0
  firebase_storage: ^3.1.0
  cloud_firestore: ^0.13.0+1
  flutter_auth_buttons: ^0.6.0
  flutter_auth0: ^0.5.0
  firebase: ^7.1.0
  microsoft_graph: ^0.0.13
  microsoft_graph_http: ^0.0.13
  oauth2: ^1.5.0
  flutter_barcode_scanner: ^0.1.7
  enum_to_string: ^1.0.8
  flutter_svg: ^0.17.1
  custom_switch: ^0.0.1
  flash: ^1.2.0
  wifi: ^0.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4


flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/Ascendere.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
   - assets/img/people.jpg
   - assets/img/ann.jpg
   - assets/img/girl.jpg
   - assets/img/mountain.jpeg
   - assets/img/beach.jpeg
   - assets/img/beach_palm.jpeg
   - assets/img/mountain_stars.jpeg
   - assets/img/sunset.jpeg
   - assets/img/river.jpeg
   - assets/img/Ascendere.png

  fonts:
    - family: Raleway
      fonts:
       - asset: fonts/Raleway-Light.ttf
    - family: Montserrat
      fonts:
       - asset: fonts/Montserrat-Regular.ttf
    - family: Lato
      fonts:
       - asset: fonts/Lato-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


